nss_ldap: Remove
- No update since 06. Nov 2009
- Fails to build here ("ldap-nss.c:1260:3: error: '__pid' undeclared")
- Uses ${LIBDIR} which suggests nobody has used it at least since the
  Great Merge, Part II
- The Internet suggests nss-pam-ldapd as a maintained fork:
  (http://arthurdejong.org/nss-pam-ldapd/)

Change-Id: I37e5934ff24f3944629902b430edd5eddb5959d3