libmng: avoid using the config.h that shipped in the archive
The config.h in the archive has for example HAVE_LIBLCMS2 set, which
results in an error, because lcms2.h can't be included if the option is
disabled and lcms2 is not installed.

Also, include stdio.h in libmng_types.h that resulted in the following
error (which only shows up when config.h is removed):

libtool: compile:  x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I/var/tmp/paludis/build/media-libs-libmng-2.0.2-r2/work/libmng-2.0.2 -march=sandybridge -mtune=ivybridge -pipe -O2 -c /var/tmp/paludis/build/media-l
ibs-libmng-2.0.2-r2/work/libmng-2.0.2/libmng_chunk_io.c  -fPIC -DPIC -o .libs/libmng_chunk_io.o
Makefile:459: recipe for target 'libmng_callback_xs.lo' failed
In file included from /var/tmp/paludis/build/media-libs-libmng-2.0.2-r2/work/libmng-2.0.2/libmng_types.h:207:0,
                 from /var/tmp/paludis/build/media-libs-libmng-2.0.2-r2/work/libmng-2.0.2/libmng.h:386,
                 from /var/tmp/paludis/build/media-libs-libmng-2.0.2-r2/work/libmng-2.0.2/libmng_callback_xs.c:63:
/usr/include/jpeglib.h:954:30: error: unknown type name 'FILE'
 EXTERN(void) jpeg_stdio_dest JPP((j_compress_ptr cinfo, FILE * outfile));
                              ^

Change-Id: I5542491d38b49b0b0108ab4d1b9c380e57e3dc76