libgcc: Version bump to 5.2.0
Also added a build dep on sys-libs/libstdc++:${SLOT} (and changed
libstdc++'s dep on libgcc from build+run to post in another commit).
Otherwise I get "In file included from
/var/tmp/paludis/build/sys-libs-libgcc-5.2.0/work/gcc-5.2.0/gcc/genconstants.c:28:0:
/var/tmp/paludis/build/sys-libs-libgcc-5.2.0/work/gcc-5.2.0/gcc/system.h:201:19:
fatal error: string: No such file or directory"
when trying to upgrade from 5.1.0 to 5.2.0.

Change-Id: Ic4095838b54a2c344c83a156c092f2bda48097dd
Reviewed-on: https://galileo.mailstation.de/gerrit/3044
Reviewed-by: Heiko Becker <heirecka@exherbo.org>